apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: maxerling/hello:latest
          imagePullPolicy: IfNotPresent